---

- block:
  - apt: update_cache=yes cache_valid_time=86400

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-pip
    tags:
    - prepare

  - name: upgrade pip
    pip:
      name: pip
      extra_args: --upgrade

  - name: install tensorflow
    pip:
      name: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp27-none-linux_x86_64.whl
      extra_args: --upgrade

  - name: install python packages
    pip: name={{ item }} state=present
    with_items:
      - keras
      - pandas
      - pillow
    tags:
    - prepare