---

- block:
  - apt: update_cache=yes cache_valid_time=86400

  - name: install packages
    apt: name=ganglia-monitor state=present

  - template: src=gmond.conf.j2 dest=/etc/ganglia/gmond.conf}

  become: true
  become_user: root
